import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/ui/Navbar";
import "./globals.css";

const ppNeue = localFont({
  src: [
    {
      path: "../../public/font/PPNeueMachina-PlainLight.otf",
      weight: "200",
      style: "inkLight",
    },
    {
      path: "../../public/font/PPNeueMachina-InktrapRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/PPNeueMachina-InktrapUltrabold.otf",
      weight: "900",
      style: "ultraBold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ppNeue.className}>
        {/* <header>
          <Navbar />
        </header> */}
        {children}
      </body>
    </html>
  );
}
