import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import Navbar from "./components/ui/Navbar";
import "./globals.css";
import QueryProvider from "./query-provider";

const ppNeue = localFont({
  src: [
    {
      path: "../../public/font/PPNeueMachina-PlainLight.otf",
      weight: "200",
      style: "inkLight",
    },
    {
      path: "../../public/font/PPNeueMachina-InktrapRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/PPNeueMachina-InktrapUltrabold.otf",
      weight: "900",
      style: "ultraBold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const supabase = createServerComponentClient({ cookies: () => cookieStore });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={ppNeue.className}>
        <QueryProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
